<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="10" passed="10">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="62" started-at="2012-07-04T22:17:44Z" finished-at="2012-07-04T22:17:45Z">
    <groups>
      <group name="unit">
        <method signature="RepositoryImplTest.testCheckoutNegative()[pri:0, instance:org.apache.ace.repository.impl.RepositoryImplTest@353c375]" name="testCheckoutNegative" class="org.apache.ace.repository.impl.RepositoryImplTest"/>
        <method signature="RepositoryImplTest.testCheckoutZero()[pri:0, instance:org.apache.ace.repository.impl.RepositoryImplTest@353c375]" name="testCheckoutZero" class="org.apache.ace.repository.impl.RepositoryImplTest"/>
        <method signature="RepositoryImplTest.testCommitAndCheckout()[pri:0, instance:org.apache.ace.repository.impl.RepositoryImplTest@353c375]" name="testCommitAndCheckout" class="org.apache.ace.repository.impl.RepositoryImplTest"/>
        <method signature="RepositoryImplTest.testCommitNegative()[pri:0, instance:org.apache.ace.repository.impl.RepositoryImplTest@353c375]" name="testCommitNegative" class="org.apache.ace.repository.impl.RepositoryImplTest"/>
        <method signature="RepositoryImplTest.testGetAndPut()[pri:0, instance:org.apache.ace.repository.impl.RepositoryImplTest@353c375]" name="testGetAndPut" class="org.apache.ace.repository.impl.RepositoryImplTest"/>
        <method signature="RepositoryImplTest.testGetNegative()[pri:0, instance:org.apache.ace.repository.impl.RepositoryImplTest@353c375]" name="testGetNegative" class="org.apache.ace.repository.impl.RepositoryImplTest"/>
        <method signature="RepositoryImplTest.testGetZero()[pri:0, instance:org.apache.ace.repository.impl.RepositoryImplTest@353c375]" name="testGetZero" class="org.apache.ace.repository.impl.RepositoryImplTest"/>
        <method signature="RepositoryImplTest.testPutNegative()[pri:0, instance:org.apache.ace.repository.impl.RepositoryImplTest@353c375]" name="testPutNegative" class="org.apache.ace.repository.impl.RepositoryImplTest"/>
        <method signature="RepositoryImplTest.testPutZero()[pri:0, instance:org.apache.ace.repository.impl.RepositoryImplTest@353c375]" name="testPutZero" class="org.apache.ace.repository.impl.RepositoryImplTest"/>
        <method signature="RepositoryImplTest.testUpdated()[pri:0, instance:org.apache.ace.repository.impl.RepositoryImplTest@353c375]" name="testUpdated" class="org.apache.ace.repository.impl.RepositoryImplTest"/>
      </group> <!-- unit -->
    </groups>
    <test name="Default test" duration-ms="62" started-at="2012-07-04T22:17:44Z" finished-at="2012-07-04T22:17:45Z">
      <class name="org.apache.ace.repository.impl.RepositoryImplTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.apache.ace.repository.impl.RepositoryImplTest@353c375]" name="setUp" is-config="true" duration-ms="13" started-at="2012-07-04T22:17:44Z" finished-at="2012-07-04T22:17:44Z">
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testCheckoutNegative()[pri:0, instance:org.apache.ace.repository.impl.RepositoryImplTest@353c375]" name="testCheckoutNegative" duration-ms="5" started-at="2012-07-04T22:17:44Z" finished-at="2012-07-04T22:17:44Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Version must be greater than 0.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Version must be greater than 0.
	at org.apache.ace.repository.impl.RepositoryImpl.checkout(RepositoryImpl.java:126)
	at org.apache.ace.repository.impl.RepositoryImplTest.testCheckoutNegative(RepositoryImplTest.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1192)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1117)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:109)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:202)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:173)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
        </test-method> <!-- testCheckoutNegative -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.apache.ace.repository.impl.RepositoryImplTest@353c375]" name="setUp" is-config="true" duration-ms="1" started-at="2012-07-04T22:17:44Z" finished-at="2012-07-04T22:17:44Z">
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testCheckoutZero()[pri:0, instance:org.apache.ace.repository.impl.RepositoryImplTest@353c375]" name="testCheckoutZero" duration-ms="1" started-at="2012-07-04T22:17:44Z" finished-at="2012-07-04T22:17:44Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Version must be greater than 0.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Version must be greater than 0.
	at org.apache.ace.repository.impl.RepositoryImpl.checkout(RepositoryImpl.java:126)
	at org.apache.ace.repository.impl.RepositoryImplTest.testCheckoutZero(RepositoryImplTest.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1192)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1117)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:109)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:202)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:173)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
        </test-method> <!-- testCheckoutZero -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.apache.ace.repository.impl.RepositoryImplTest@353c375]" name="setUp" is-config="true" duration-ms="1" started-at="2012-07-04T22:17:44Z" finished-at="2012-07-04T22:17:44Z">
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testCommitAndCheckout()[pri:0, instance:org.apache.ace.repository.impl.RepositoryImplTest@353c375]" name="testCommitAndCheckout" duration-ms="1" started-at="2012-07-04T22:17:44Z" finished-at="2012-07-04T22:17:44Z">
        </test-method> <!-- testCommitAndCheckout -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.apache.ace.repository.impl.RepositoryImplTest@353c375]" name="setUp" is-config="true" duration-ms="1" started-at="2012-07-04T22:17:44Z" finished-at="2012-07-04T22:17:44Z">
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testCommitNegative()[pri:0, instance:org.apache.ace.repository.impl.RepositoryImplTest@353c375]" name="testCommitNegative" duration-ms="1" started-at="2012-07-04T22:17:44Z" finished-at="2012-07-04T22:17:44Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Version must be greater than or equal to 0.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Version must be greater than or equal to 0.
	at org.apache.ace.repository.impl.RepositoryImpl.commit(RepositoryImpl.java:137)
	at org.apache.ace.repository.impl.RepositoryImplTest.testCommitNegative(RepositoryImplTest.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1192)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1117)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:109)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:202)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:173)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
        </test-method> <!-- testCommitNegative -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.apache.ace.repository.impl.RepositoryImplTest@353c375]" name="setUp" is-config="true" duration-ms="1" started-at="2012-07-04T22:17:44Z" finished-at="2012-07-04T22:17:44Z">
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testGetAndPut()[pri:0, instance:org.apache.ace.repository.impl.RepositoryImplTest@353c375]" name="testGetAndPut" duration-ms="1" started-at="2012-07-04T22:17:44Z" finished-at="2012-07-04T22:17:44Z">
        </test-method> <!-- testGetAndPut -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.apache.ace.repository.impl.RepositoryImplTest@353c375]" name="setUp" is-config="true" duration-ms="0" started-at="2012-07-04T22:17:44Z" finished-at="2012-07-04T22:17:44Z">
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testGetNegative()[pri:0, instance:org.apache.ace.repository.impl.RepositoryImplTest@353c375]" name="testGetNegative" duration-ms="1" started-at="2012-07-04T22:17:44Z" finished-at="2012-07-04T22:17:44Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Version must be greater than 0.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Version must be greater than 0.
	at org.apache.ace.repository.impl.RepositoryImpl.checkout(RepositoryImpl.java:126)
	at org.apache.ace.repository.impl.RepositoryImpl.get(RepositoryImpl.java:75)
	at org.apache.ace.repository.impl.RepositoryImplTest.testGetNegative(RepositoryImplTest.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1192)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1117)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:109)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:202)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:173)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
        </test-method> <!-- testGetNegative -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.apache.ace.repository.impl.RepositoryImplTest@353c375]" name="setUp" is-config="true" duration-ms="1" started-at="2012-07-04T22:17:44Z" finished-at="2012-07-04T22:17:44Z">
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testGetZero()[pri:0, instance:org.apache.ace.repository.impl.RepositoryImplTest@353c375]" name="testGetZero" duration-ms="1" started-at="2012-07-04T22:17:44Z" finished-at="2012-07-04T22:17:44Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Version must be greater than 0.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Version must be greater than 0.
	at org.apache.ace.repository.impl.RepositoryImpl.checkout(RepositoryImpl.java:126)
	at org.apache.ace.repository.impl.RepositoryImpl.get(RepositoryImpl.java:75)
	at org.apache.ace.repository.impl.RepositoryImplTest.testGetZero(RepositoryImplTest.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1192)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1117)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:109)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:202)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:173)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
        </test-method> <!-- testGetZero -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.apache.ace.repository.impl.RepositoryImplTest@353c375]" name="setUp" is-config="true" duration-ms="1" started-at="2012-07-04T22:17:44Z" finished-at="2012-07-04T22:17:44Z">
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testPutNegative()[pri:0, instance:org.apache.ace.repository.impl.RepositoryImplTest@353c375]" name="testPutNegative" duration-ms="1" started-at="2012-07-04T22:17:44Z" finished-at="2012-07-04T22:17:44Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Version must be greater than 0.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Version must be greater than 0.
	at org.apache.ace.repository.impl.RepositoryImpl.put(RepositoryImpl.java:80)
	at org.apache.ace.repository.impl.RepositoryImplTest.testPutNegative(RepositoryImplTest.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1192)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1117)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:109)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:202)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:173)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
        </test-method> <!-- testPutNegative -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.apache.ace.repository.impl.RepositoryImplTest@353c375]" name="setUp" is-config="true" duration-ms="1" started-at="2012-07-04T22:17:44Z" finished-at="2012-07-04T22:17:44Z">
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testPutZero()[pri:0, instance:org.apache.ace.repository.impl.RepositoryImplTest@353c375]" name="testPutZero" duration-ms="1" started-at="2012-07-04T22:17:44Z" finished-at="2012-07-04T22:17:44Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Version must be greater than 0.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Version must be greater than 0.
	at org.apache.ace.repository.impl.RepositoryImpl.put(RepositoryImpl.java:80)
	at org.apache.ace.repository.impl.RepositoryImplTest.testPutZero(RepositoryImplTest.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1192)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1117)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:109)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:202)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:173)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
        </test-method> <!-- testPutZero -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.apache.ace.repository.impl.RepositoryImplTest@353c375]" name="setUp" is-config="true" duration-ms="1" started-at="2012-07-04T22:17:44Z" finished-at="2012-07-04T22:17:44Z">
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testUpdated()[pri:0, instance:org.apache.ace.repository.impl.RepositoryImplTest@353c375]" name="testUpdated" duration-ms="0" started-at="2012-07-04T22:17:44Z" finished-at="2012-07-04T22:17:44Z">
          <exception class="java.lang.IllegalStateException">
            <message>
              <![CDATA[Commit is only permitted on master repositories]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalStateException: Commit is only permitted on master repositories
	at org.apache.ace.repository.impl.RepositoryImpl.commit(RepositoryImpl.java:134)
	at org.apache.ace.repository.impl.RepositoryImplTest.testUpdated(RepositoryImplTest.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1192)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1117)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:109)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:202)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:173)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalStateException -->
        </test-method> <!-- testUpdated -->
      </class> <!-- org.apache.ace.repository.impl.RepositoryImplTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
